export const LOAD_APP = 'LOAD_APP'

// Products Data Types
export const PRODUCTS_DATA_ALREADY_LOADED = 'PRODUCTS_DATA_ALREADY_LOADED'
export const LOAD_PRODUCTS_DATA = 'LOAD_PRODUCTS_DATA'
export const LOAD_PRODUCTS_DATA_REQUEST = 'LOAD_PRODUCTS_DATA_REQUEST'
export const LOAD_PRODUCTS_DATA_SUCCESS = 'LOAD_PRODUCTS_DATA_SUCCESS'
export const LOAD_PRODUCTS_DATA_FAILURE = 'LOAD_PRODUCTS_DATA_FAILURE'
